---
- name: Remove Apache
  yum:
    name: httpd
    state: absent
- name: Remove useless dir
  shell: "rm -rf /var/www/html/"
  tags:
    - nginx
  notify: Restart Nginx

- name: Ensure APT official nginx key
  ansible.builtin.rpm_key:
    state: present
    key: http://nginx.org/keys/nginx_signing.key

- name: Ensure APT official nginx repository
  yum: name="deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"

- name: Ensure APT official nginx repository (mainline)
  yum: name="deb http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"

- name: mkdir and —Åopy prod
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'
 
- name: copy file
  ansible.builtin.copy:
    src: ./files/index.php
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0644'

- name: Install Nginx web server
  yum:
    name: nginx={{nginx_version}}
    state: present
  notify: Restart Nginx
  tags:
    - nginx

- name: Remove Nginx default
  shell: "rm -rf /etc/nginx/conf.d/default.conf"
  tags:
    - nginx
  notify: Restart Nginx

- name: Update nginx configs
  become: true
  template:
    src: templates/nginx.conf
    dest: "/etc/nginx/nginx.conf"
  tags:
    - nginx
  notify: Restart Nginx

- name: Update nginx config files
  become: true
  template:
    src: templates/nginx1.conf
    dest: "/etc/nginx/sites-available/default"
  tags:
    - nginx
  notify: Restart Nginx

- name: link nginx config
  become: true
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
  tags:
    - nginx
  notify: Restart Nginx