- name: Restart PHP-FPM
  service:
    name: php{{php_version}}-fpm
    state: restarted
    
- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: start mysql
  service: 
    name: mysql
    enabled: yes
    state: started
- name: restart mysql
  service: 
    name: mysql
    enabled: yes
    state: restarted