- name: Restart PHP-FPM
  service:
    name: php{{php_version}}-fpm
    state: restarted
  when: ansible_os_family == 'Debian'

- name: Restart PHP-FPM
  service:
    name: php-fpm
    state: restarted
  when: ansible_os_family == 'RedHat'
    
- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: start mysql
  service: 
    name: mysql
    enabled: yes
    state: started
- name: restart mysql
  service: 
    name: mysql
    enabled: yes
    state: restarted