---
#- name: Ensure APT official mysql repository
#  apt_repository: repo="deb http://repo.mysql.com/apt/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} msyql-{{ mysql_version }}" update-cache=yes

- name: Install MySQL DB server
  apt:
    name: mysql-server
    state: latest
  tags:
     - mysql-db

- name: Install python3-mysqldb
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python3-mysqldb

  tags:
     - mysql-db

- mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_pass}}"
    priv: '*.*:ALL'
    state: present
  tags:
     - mysql-db

- name:  Create APP DB database
  mysql_db: name="{{mysql_db}}" state=present login_user="{{mysql_user}}" login_password="{{mysql_pass}}"