---
- name: install python3
  yum:
    name: python3
    state: latest
  become: yes

- name: Install MySQL DB server
  yum:
    name: mysql-server
    state: latest
  tags:
     - mysql-db

- name: Install python3-mysqldb
  pip: name={{item}} state=latest
  with_items:
    - pymysql
  tags:
     - mysql-db

- name: MySQL | Config for easy access as root user
  template: src=my.cnf dest=/root/.my.cnf
  become: yes


- mysql_user:
    name: "{{mysql_user}}"
    password: "{{mysql_pass}}"
    priv: '*.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  tags:
     - mysql-db

- name:  Create APP DB database
  mysql_db: name="{{mysql_db}}" state=present login_user="{{mysql_user}}" login_password="{{mysql_pass}}"

- name: restart mysql
  service: name=mysql state=restarted
  become: yes