---
- name: Ensure required packages to add Ondřej Surý's PHP repository
  apt:
    pkg:
      - apt-transport-https
      - lsb-release
      - ca-certificates
    state: present
    update_cache: yes
  become: yes
  tags:
     - php


- name: Add Sury's APT key (Debian)
  apt_key: url="https://packages.sury.org/php/apt.gpg" state=present
  when: ansible_distribution == 'Debian'
  tags:
     - php


- name: Add Sury's APT repository (Debian)
  apt_repository: repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main" state=present update_cache=yes
  when: ansible_distribution == 'Debian'
  tags:
     - php

- name: Install PHP {{php_version}} PPA Repo
  apt_repository:
    repo: 'ppa:ondrej/php'
  when: ansible_distribution == 'Ubuntu'
  tags:
     - php

- name: Install PHP {{php_version}}
  apt: name=php{{php_version}} state=latest

- name: Install PHP packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php{{php_version}}-curl
    - php{{php_version}}-fpm
    - php{{php_version}}-intl
    - php{{php_version}}-mysql
    - php{{php_version}}-xml
    - php{{php_version}}-mbstring
    - php{{php_version}}-cli
    - php{{php_version}}-common
    - php{{php_version}}-json
    - php{{php_version}}-gd
    - php{{php_version}}-mcrypt
    - php{{php_version}}-odbc
    - php{{php_version}}-pgsql
    - php{{php_version}}-xmlrpc
    - php{{php_version}}-opcache
    - php{{php_version}}-bz2
  notify: Restart PHP-FPM
  tags:
     - php