---

- name: epel repo 
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: download remi release repo for php
  get_url: url=https://rpms.remirepo.net/enterprise/remi-release-8.rpm dest=/tmp/remi-release-8.rpm
  tags: php-fpm

- name: install remi repo
  shell: /bin/rpm -Uvh /tmp/remi-release-8.rpm
  register: remi_repo_result
  failed_when: "'conflict' in remi_repo_result.stderr"
  tags: php-fpm

- name: Ensure dnf-plugins are installed on CentOS 8+.
  yum:
    name: dnf-plugins-core
    state: present
  tags:
     - php


- name: Enable DNF module for CentOS 8+.
  shell: |
    dnf config-manager --set-enabled powertools
    dnf module enable -y php:remi-7.4
  args:
    warn: false
  register: dnf_module_enable
  tags:
     - php

- name: Install PHP packages
  become: true
  dnf: name={{ item }} state=latest enablerepo=remi,remi-php74
  with_items:
    - php-fpm
    - php-common
    - php-devel
    - php-cli
    - php-pdo
    - php-gd
    - php-xml
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-igbinary
    - php-bcmath
    - php-opcache
  notify: Restart PHP-FPM
  tags:
     - php